### ISSUE TITLE
Implement Azure collector plugin

### ISSUE THREAD

**Issue by lloesche** [someengineering/fixinventory#65]

**Comment by homotechsual** [comment]
+1 on having Azure available. We don't do much with AWS or GCP but we've got 112 K8S clusters across 50+ Azure accounts/subscriptions. So multi-tenant functionality would be fantastic as well if possible.

**Comment by srikrishnan237** [comment]
+1 on azure and  multi-tenant functionality. 

on that note, i see that the azure collector plugins are available on github, but i do not see the same on the docs. 

would this be available anytime soon? 


thank you!

**Comment by aquamatthias** [comment]
> would this be available anytime soon?

We are actively working on that topic - so yes it should be available soon.
