### ISSUE TITLE
Resources Automations - start/stop plan

### ISSUE THREAD

**Issue by 050rotemlevi** [someengineering/fixinventory#850]
### Motivation

most of sandbox / dev accounts dont needs to work in non-working hours
i want a Start/Stop plan that i can configure

### Desired Behavior

I create new plan (start / stop)
choose account
choose region/s
<img width="1102" alt="Screen Shot 2022-05-10 at 1 23 32" src="https://user-images.githubusercontent.com/30467500/167508921-5a693c76-aac2-4ea4-97c9-7eb4c1e09675.png">
<img width="1105" alt="Screen Shot 2022-05-10 at 1 23 45" src="https://user-images.githubusercontent.com/30467500/167508930-8ac15d13-6fd0-4836-a5e9-2da8bec7fd3a.png">
<img width="1095" alt="Screen Shot 2022-05-10 at 1 24 16" src="https://user-images.githubusercontent.com/30467500/167508932-7ea604cf-ed2d-45ce-a7be-c325146d6254.png">
<img width="1096" alt="Screen Shot 2022-05-10 at 1 25 00" src="https://user-images.githubusercontent.com/30467500/167508934-d4781854-4a66-4875-ad79-116f9d0e2448.png">

choose resources and filter (Tag for example) 

### Additional Context

[aws_actions (1).txt](https://github.com/someengineering/resoto/files/8655785/aws_actions.1.txt)

**Comment by lloesche** [comment]
@050rotemlevi thank you for this issue! We're working on adding more actions in addition to `tag` and `clean`.
